/*

 MAPPOINTS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : mappointst.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mappointsWidth 20
#define mappointsHeight 18
#define mappointsBank 0

#define mappoints mappointsPLN0
extern unsigned char mappointsPLN0[];

/* End of MAPPOINTS.H */
