/*

 MAPPOINTST.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 79

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __mappointst_h_INCLUDE
#define __mappointst_h_INCLUDE

/* Bank of tiles. */
#define mappointstBank 0

/* Super Gameboy palette 0 */
#define mappointstSGBPal0c0 0
#define mappointstSGBPal0c1 0
#define mappointstSGBPal0c2 0
#define mappointstSGBPal0c3 0

/* Super Gameboy palette 1 */
#define mappointstSGBPal1c0 6076
#define mappointstSGBPal1c1 8935
#define mappointstSGBPal1c2 6596
#define mappointstSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define mappointstSGBPal2c0 6076
#define mappointstSGBPal2c1 8935
#define mappointstSGBPal2c2 6596
#define mappointstSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define mappointstSGBPal3c0 6076
#define mappointstSGBPal3c1 8935
#define mappointstSGBPal3c2 6596
#define mappointstSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define mappointstCGBPal0c0 32767
#define mappointstCGBPal0c1 9023
#define mappointstCGBPal0c2 127
#define mappointstCGBPal0c3 0

/* Gameboy Color palette 1 */
#define mappointstCGBPal1c0 6076
#define mappointstCGBPal1c1 8935
#define mappointstCGBPal1c2 6596
#define mappointstCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define mappointstCGBPal2c0 6076
#define mappointstCGBPal2c1 8935
#define mappointstCGBPal2c2 6596
#define mappointstCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define mappointstCGBPal3c0 6076
#define mappointstCGBPal3c1 8935
#define mappointstCGBPal3c2 6596
#define mappointstCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define mappointstCGBPal4c0 6076
#define mappointstCGBPal4c1 8935
#define mappointstCGBPal4c2 6596
#define mappointstCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define mappointstCGBPal5c0 6076
#define mappointstCGBPal5c1 8935
#define mappointstCGBPal5c2 6596
#define mappointstCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define mappointstCGBPal6c0 6076
#define mappointstCGBPal6c1 8935
#define mappointstCGBPal6c2 6596
#define mappointstCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define mappointstCGBPal7c0 6076
#define mappointstCGBPal7c1 8935
#define mappointstCGBPal7c2 6596
#define mappointstCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char mappointst[];

#endif

/* End of MAPPOINTST.H */
